services:
  rabbitmq:
    build:
      context: ./rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  database: null
